DCAF.Air
    -- adds a list of air adversaries to be supported in the mission (1st arg is display name; 2nd arg is name of late activated group in miz)
    :InitCategory(DCAF.AirCategory:New("BVR")
        :WithOptions(DCAF.AirOptions:New():SetMaxOffsetAngle(0))
        -- :WithGroup("Su-33", "RED Su-33_bvr")
        -- :WithGroup("Su-30", "RED Su-30_bvr")
        -- :WithGroup("Su-27", "RED Su-27_bvr")
        :WithGroup("Mig-29S", "RED Mig-29S_bvr")
        -- :WithGroup("Mig-29A", "RED Mig-29A_bvr")
        -- :WithGroup("Mig-23", "RED Mig-23_bvr")
        -- :WithGroup("Mig-21", "RED Mig-21_bvr")
        -- :WithGroup("JF-17", "RED JF-17_bvr")
        -- :WithGroup("Mirage 2000C", "RED M2000C_bvr")
        -- :WithGroup("Mirage 2000-5", "RED M2000-5_bvr")
        -- :WithGroup("Mirage F1CE", "RED Mirage F1CE_bvr")
        -- :WithGroup("F-14A-GR", "RED F-14A-GR_bvr")
        -- :WithGroup("F-15E", "RED F-15E_bvr")
        -- :WithGroup("FA-18C", "RED FA-18C_bvr")
        -- :WithGroup("F-16C", "RED F-16C_bvr")
        -- :WithGroup("F-4E", "RED F-F4E_bvr")
        -- :WithGroup("F-5E3", "RED F-F5E3_bfm")
    )
    :InitCategory(DCAF.AirCategory:New("Offensive BFM")
        :WithOptions(DCAF.AirOptions:New():SetDistance(DCAF.AirDistance["3000ft"]):SetMaxOffsetAngle(5):SetAspect(DCAF.AirAspect.Cold))
        -- :WithGroup("Su-33", "RED Su-33_bfm")
        -- :WithGroup("Su-30", "RED Su-30_bfm")
        -- :WithGroup("Su-27", "RED Su-27_bfm")
        :WithGroup("Mig-29S", "RED Mig-29S_bfm")
        -- :WithGroup("Mig-29A", "RED Mig-29A_bfm")
        -- :WithGroup("Mig-23", "RED Mig-23_bfm")
        -- :WithGroup("Mig-21", "RED Mig-21_bfm")
        -- :WithGroup("JF-17", "RED JF-17_bfm")
        -- :WithGroup("Mirage 2000C", "RED M2000C_bfm")
        -- :WithGroup("Mirage 2000-5", "RED M2000-5_bfm")
        -- :WithGroup("Mirage F1CE", "RED Mirage F1CE_bfm")
        -- :WithGroup("F-14A-GR", "RED F-14A-GR_bvr")
        -- :WithGroup("F-15E", "RED F-15E_bvr")
        -- :WithGroup("FA-18C", "RED FA-18C_bvr")
        -- :WithGroup("F-16C", "RED F-16C_bvr")
        -- :WithGroup("F-4E", "RED F-F4E_bvr")
        -- :WithGroup("F-5E3", "RED F-F5E3_bfm")
    )

    :InitCategory(DCAF.AirCategory:New("Defensive BFM")
        :WithOptions(DCAF.AirOptions:New():SetDistance(DCAF.AirDistance["3000ft"]):SetMaxOffsetAngle(5):SetPosition(DCAF.AirPosition.Behind))
        -- :WithGroup("Su-33", "RED Su-33_bfm")
        -- :WithGroup("Su-30", "RED Su-30_bfm")
        -- :WithGroup("Su-27", "RED Su-27_bfm")
        :WithGroup("Mig-29S", "RED Mig-29S_bfm")
        -- :WithGroup("Mig-29A", "RED Mig-29A_bfm")
        -- :WithGroup("Mig-23", "RED Mig-23_bfm")
        -- :WithGroup("Mig-21", "RED Mig-21_bfm")
        -- :WithGroup("JF-17", "RED JF-17_bfm")
        -- :WithGroup("Mirage 2000C", "RED M2000C_bfm")
        -- :WithGroup("Mirage 2000-5", "RED M2000-5_bfm")
        -- :WithGroup("Mirage F1CE", "RED Mirage F1CE_bfm")
        -- :WithGroup("F-14A-GR", "RED F-14A-GR_bvr")
        -- :WithGroup("F-15E", "RED F-15E_bvr")
        -- :WithGroup("FA-18C", "RED FA-18C_bvr")
        -- :WithGroup("F-16C", "RED F-16C_bvr")
        -- :WithGroup("F-4E", "RED F-F4E_bvr")
        -- :WithGroup("F-5E3", "RED F-F5E3_bfm")
    )

    -- :InitCategory(DCAF.AirCategory:New("Civilian")
    --     :WithOptions(DCAF.AirOptions:New():SetBehavior(DCAF.AirBehavior.SittingDuck))
    --     :WithGroup("Boeing 747", "NEU B747_civ")
    --     :WithGroup("Boeing 757", "NEU B757_civ")
    --     :WithGroup("Hercules C-130", "BLU C130_civ")
    --     :WithGroup("Private Cessna P210", "BLU CP210_civ"))

    -- :InitCAP(DCAF.CAPZone:New("RED CAP East", 230, 25000, NauticalMiles(15))
    --     :WithGroup("Su-33", "RED Su-33_bvr")
    --     :WithGroup("Su-30", "RED Su-30_bvr")
    --     :WithGroup("Su-27", "RED Su-27_bvr", 2)
    --     :WithGroup("Mig-29S", "RED Mig-29S_bvr", 2)
    --     :WithGroup("Mig-29A", "RED Mig-29A_bvr")
    --     :WithGroup("Mig-23", "RED Mig-23_bvr")
    --     :WithGroup("Mig-21", "RED Mig-21_bvr")
    --     :WithGroup("JF-17", "RED JF-17_bvr")
    --     :WithGroup("Mirage 2000C", "RED M2000C_bvr")
    --     :WithGroup("Mirage 2000-5", "RED M2000-5_bvr")
    --     :WithGroup("Mirage F1CE", "RED Mirage F1CE_bvr"))

    -- :WithGroupRandomization()  -- << -- randomizes air threats (accepts an #DCAF.Air.Randomization as argument)
    :WithGroupMenus("A-A")     -- << -- builds menus for all groups (or specified group), as players enter aircrafts/units, to manually spawn air threats
    :Start()

-------------------------- DONE -----------------------------            
Debug("\\\\\\\\\\\\\\\\\\\\ DCAF.SYR_Training_AA.lua was loaded ///////////////////")