state = {
 ["Statics"] = {
   [1] = {
     ["Pos"] = {
       ["y"] = 9.3406934738159,
       ["x"] = -291055.4375,
       ["z"] = 645404.5,
     },
     ["Lfe"] = 0,
     ["Snm"] = "TEST Static",
     ["_static"] = {
       ["StaticName"] = "TEST Static",
       ["ClassName"] = "STATIC",
       ["Life0"] = 500,
     },
     ["Hdg"] = 118.00000434695,
   },
 },
 ["DateTime"] = {
   ["Year"] = 2016,
   ["Month"] = 6,
   ["Time"] = 36093,
   ["Day"] = 21,
   ["DayOffset"] = 0,
 },
 ["Groups"] = {
   [1] = {
     ["Spn"] = false,
     ["Uns"] = {
       [1] = {
         ["Idx"] = 1,
         ["Lfe"] = 1,
         ["Vel"] = 4.3491294524075,
         ["Tim"] = 36093,
         ["Pos"] = {
           ["y"] = 9.2444212605219,
           ["x"] = -292121.19085317,
           ["z"] = 650007.67418231,
         },
         ["Hdg"] = 1.2534302621258,
         ["Unm"] = "TEST-Target-1",
       },
       [2] = {
         ["Idx"] = 2,
         ["Lfe"] = 1,
         ["Vel"] = 4.5634298760954,
         ["Tim"] = 36093,
         ["Pos"] = {
           ["y"] = 9.2968720621266,
           ["x"] = -292166.7768462,
           ["z"] = 650006.67701642,
         },
         ["Hdg"] = 1.2533764552297,
         ["Unm"] = "TEST-Target-2",
       },
       [3] = {
         ["Idx"] = 3,
         ["Lfe"] = 1,
         ["Vel"] = 4.5680630045108,
         ["Tim"] = 36093,
         ["Pos"] = {
           ["y"] = 9.3315207599815,
           ["x"] = -292196.89124557,
           ["z"] = 650006.01826882,
         },
         ["Hdg"] = 1.2533763485335,
         ["Unm"] = "TEST-Target-3",
       },
       [4] = {
         ["Idx"] = 4,
         ["Lfe"] = 1,
         ["Vel"] = 4.5795351028381,
         ["Tim"] = 36093,
         ["Pos"] = {
           ["y"] = 9.3661377001708,
           ["x"] = -292226.97832223,
           ["z"] = 650005.3601192,
         },
         ["Hdg"] = 1.2533756016598,
         ["Unm"] = "TEST-Target-4",
       },
     },
     ["Tnm"] = "TEST-Target",
     ["Gnm"] = "TEST-Target",
   },
   [2] = {
     ["Spn"] = false,
     ["Uns"] = {
       [1] = {
         ["Idx"] = 1,
         ["Lfe"] = -inf,
         ["Vel"] = 0,
         ["Tim"] = 36060,
         ["Pos"] = {
           ["y"] = 9.4663046614437,
           ["x"] = -291040.31250895,
           ["z"] = 645416.75000094,
         },
         ["Unm"] = "TEST-BehindStatic-1",
       },
     },
     ["Tnm"] = "TEST-BehindStatic",
     ["Gnm"] = "TEST-BehindStatic",
   },
   [3] = {
     ["Spn"] = false,
     ["Uns"] = {
       [1] = {
         ["Idx"] = 1,
         ["Lfe"] = 1,
         ["Vel"] = 0,
         ["Tim"] = 36093,
         ["Pos"] = {
           ["y"] = 6.9477157857867,
           ["x"] = -291673.43750175,
           ["z"] = 645401.06250552,
         },
         ["Hdg"] = 77.086641712745,
         ["Unm"] = "TEST-M1A2-1",
       },
     },
     ["Tnm"] = "TEST-M1A2",
     ["Gnm"] = "TEST-M1A2",
   },
 },
 ["Templates"] = {
   ["TEST-Target"] = {
     ["visible"] = false,
     ["CountryID"] = 0,
     ["lateActivation"] = false,
     ["tasks"] = {
     },
     ["uncontrollable"] = false,
     ["CategoryID"] = 2,
     ["task"] = "Ground Nothing",
     ["probability"] = 1,
     ["taskSelected"] = true,
     ["route"] = {
       ["routeRelativeTOT"] = false,
       ["points"] = {
         [1] = {
           ["speed_locked"] = true,
           ["type"] = "Turning Point",
           ["ETA"] = 0,
           ["ETA_locked"] = true,
           ["y"] = 649995.13907256,
           ["formation_template"] = "",
           ["x"] = -292574.88810162,
           ["alt"] = 10,
           ["speed"] = 5.6527777777778,
           ["action"] = "Off Road",
           ["task"] = {
             ["id"] = "ComboTask",
             ["params"] = {
               ["tasks"] = {
                 [1] = {
                   ["enabled"] = true,
                   ["auto"] = true,
                   ["id"] = "WrappedAction",
                   ["number"] = 1,
                   ["params"] = {
                     ["action"] = {
                       ["id"] = "EPLRS",
                       ["params"] = {
                         ["value"] = true,
                         ["groupId"] = 2,
                       },
                     },
                   },
                 },
               },
             },
           },
           ["alt_type"] = "BARO",
         },
         [2] = {
           ["speed_locked"] = true,
           ["type"] = "Turning Point",
           ["ETA"] = 82.420868996702,
           ["ETA_locked"] = false,
           ["y"] = 650007.91412315,
           ["formation_template"] = "",
           ["x"] = -292109.15642223,
           ["alt"] = 9,
           ["speed"] = 5.6527777777778,
           ["action"] = "Off Road",
           ["task"] = {
             ["id"] = "ComboTask",
             ["params"] = {
               ["tasks"] = {
                 [1] = {
                   ["number"] = 1,
                   ["auto"] = false,
                   ["id"] = "GoToWaypoint",
                   ["enabled"] = true,
                   ["params"] = {
                     ["fromWaypointIndex"] = 2,
                     ["nWaypointIndx"] = 1,
                   },
                 },
               },
             },
           },
           ["alt_type"] = "BARO",
         },
       },
     },
     ["groupId"] = 4,
     ["SpawnCategoryID"] = 2,
     ["hidden"] = false,
     ["units"] = {
       [1] = {
         ["type"] = "mrap_mk19",
         ["unitId"] = 10,
         ["skill"] = "Average",
         ["AddPropVehicle"] = {
           ["armor"] = true,
         },
         ["y"] = 649995.13907256,
         ["coldAtStart"] = false,
         ["name"] = "TEST-Target-1",
         ["playerCanDrive"] = true,
         ["x"] = -292574.88810162,
         ["heading"] = 0.027423189321203,
       },
       [2] = {
         ["type"] = "mrap_mk19",
         ["unitId"] = 11,
         ["skill"] = "Average",
         ["AddPropVehicle"] = {
           ["armor"] = true,
         },
         ["y"] = 649995.13907256,
         ["coldAtStart"] = false,
         ["name"] = "TEST-Target-2",
         ["playerCanDrive"] = true,
         ["x"] = -292614.88810162,
         ["heading"] = 0.027423189321203,
       },
       [3] = {
         ["type"] = "mrap_mk19",
         ["unitId"] = 12,
         ["skill"] = "Average",
         ["AddPropVehicle"] = {
           ["armor"] = true,
         },
         ["y"] = 649995.13907256,
         ["coldAtStart"] = false,
         ["name"] = "TEST-Target-3",
         ["playerCanDrive"] = true,
         ["x"] = -292654.88810162,
         ["heading"] = 0.027423189321203,
       },
       [4] = {
         ["type"] = "mrap_mk19",
         ["unitId"] = 13,
         ["skill"] = "Average",
         ["AddPropVehicle"] = {
           ["armor"] = true,
         },
         ["y"] = 649995.13907256,
         ["coldAtStart"] = false,
         ["name"] = "TEST-Target-4",
         ["playerCanDrive"] = true,
         ["x"] = -292694.88810162,
         ["heading"] = 0.027423189321203,
       },
     },
     ["y"] = 649995.13907256,
     ["x"] = -292574.88810162,
     ["name"] = "TEST-Target",
     ["SpawnCoalitionID"] = 1,
     ["SpawnCountryID"] = 0,
     ["CoalitionID"] = 1,
     ["start_time"] = 0,
   },
   ["TEST-BehindStatic"] = {
     ["visible"] = false,
     ["CountryID"] = 0,
     ["SpawnCoalitionID"] = 1,
     ["tasks"] = {
     },
     ["uncontrollable"] = false,
     ["CategoryID"] = 2,
     ["task"] = "Ground Nothing",
     ["taskSelected"] = true,
     ["route"] = {
       ["points"] = {
         [1] = {
           ["speed_locked"] = true,
           ["type"] = "Turning Point",
           ["ETA"] = 0,
           ["ETA_locked"] = true,
           ["y"] = 645416.77917903,
           ["formation_template"] = "",
           ["x"] = -291040.31398344,
           ["alt"] = 9,
           ["speed"] = 0,
           ["action"] = "Off Road",
           ["task"] = {
             ["id"] = "ComboTask",
             ["params"] = {
               ["tasks"] = {
                 [1] = {
                   ["enabled"] = true,
                   ["auto"] = true,
                   ["id"] = "WrappedAction",
                   ["number"] = 1,
                   ["params"] = {
                     ["action"] = {
                       ["id"] = "EPLRS",
                       ["params"] = {
                         ["value"] = true,
                         ["groupId"] = 5,
                       },
                     },
                   },
                 },
               },
             },
           },
           ["alt_type"] = "BARO",
         },
       },
     },
     ["groupId"] = 9,
     ["SpawnCategoryID"] = 2,
     ["hidden"] = false,
     ["units"] = {
       [1] = {
         ["type"] = "mrap_mk19",
         ["unitId"] = 18,
         ["skill"] = "Average",
         ["AddPropVehicle"] = {
           ["armor"] = true,
         },
         ["y"] = 645416.77917903,
         ["coldAtStart"] = false,
         ["name"] = "TEST-BehindStatic-1",
         ["playerCanDrive"] = false,
         ["x"] = -291040.31398344,
         ["heading"] = 1.5882496193148,
       },
     },
     ["y"] = 645416.77917903,
     ["x"] = -291040.31398344,
     ["name"] = "TEST-BehindStatic",
     ["start_time"] = 0,
     ["CoalitionID"] = 1,
     ["SpawnCountryID"] = 0,
   },
   ["TEST-M1A2"] = {
     ["visible"] = false,
     ["CountryID"] = 2,
     ["lateActivation"] = true,
     ["tasks"] = {
     },
     ["uncontrollable"] = false,
     ["CategoryID"] = 2,
     ["task"] = "Ground Nothing",
     ["taskSelected"] = true,
     ["route"] = {
       ["routeRelativeTOT"] = true,
       ["points"] = {
         [1] = {
           ["speed_locked"] = true,
           ["type"] = "Turning Point",
           ["ETA"] = 0,
           ["ETA_locked"] = true,
           ["y"] = 645401.05364527,
           ["formation_template"] = "",
           ["x"] = -291673.44277144,
           ["alt"] = 7,
           ["speed"] = 0,
           ["action"] = "Off Road",
           ["task"] = {
             ["id"] = "ComboTask",
             ["params"] = {
               ["tasks"] = {
                 [1] = {
                   ["enabled"] = true,
                   ["auto"] = true,
                   ["id"] = "WrappedAction",
                   ["number"] = 1,
                   ["params"] = {
                     ["action"] = {
                       ["id"] = "EPLRS",
                       ["params"] = {
                         ["value"] = true,
                         ["groupId"] = 4,
                       },
                     },
                   },
                 },
                 [2] = {
                   ["enabled"] = true,
                   ["auto"] = false,
                   ["id"] = "FireAtPoint",
                   ["number"] = 2,
                   ["params"] = {
                     ["y"] = 645408.08565424,
                     ["expendQtyEnabled"] = false,
                     ["expendQty"] = 1,
                     ["alt_type"] = 1,
                     ["x"] = -291060.50679768,
                     ["templateId"] = "",
                     ["weaponType"] = 52613349374,
                     ["zoneRadius"] = 0,
                   },
                 },
               },
             },
           },
           ["alt_type"] = "BARO",
         },
       },
     },
     ["groupId"] = 8,
     ["SpawnCategoryID"] = 2,
     ["hidden"] = false,
     ["units"] = {
       [1] = {
         ["heading"] = 1.3454157339819,
         ["unitId"] = 17,
         ["skill"] = "Average",
         ["y"] = 645401.05364527,
         ["coldAtStart"] = false,
         ["name"] = "TEST-M1A2-1",
         ["playerCanDrive"] = true,
         ["x"] = -291673.44277144,
         ["type"] = "M-1 Abrams",
       },
     },
     ["y"] = 645401.05364527,
     ["x"] = -291673.44277144,
     ["name"] = "TEST-M1A2",
     ["SpawnCoalitionID"] = 2,
     ["SpawnCountryID"] = 2,
     ["CoalitionID"] = 2,
     ["start_time"] = 0,
   },
 },
}